language: python
python:
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
# command to run tests
script:
  - pytest tests/ --cov=morpho --cov-report=term-missing
  - mypy --ignore-missing-imports morpho/
after_success: coveralls
